---
- hosts: web
  vars_prompt:

    - name: cmd1
      prompt: 'Введите команду?'
      private: no

    - name: cmd2
      prompt: 'Введите  еще команду?'
      private: no

  tasks:
    - name: Input command
      shell: '{{ cmd1 }}'
      register: result1
    - name: Debug
      debug:
        var: result1

    - name: Input
      shell: '{{ cmd2 }}'
      register: result2

    - name: Debug
      debug:
        var: result2

    - name: shell
      shell: date +'%d-%m-%Y'
      register: date_for_file

    - name: Create Report
      template:
        src: '../../templates/report2.txt'
        dest: '/tmp/{{ ansible_hostname }}_02_{{ date_for_file.stdout}}.txt'
        # mode: 0644


    - name: create directory
      file:
        path: /ansible/audit/linux_severs #?Тут опечатка в задании или так надо
        state: directory
        mode: 0777
      delegate_to: localhost


    - name: Fetch
      fetch:
        src: '/tmp/{{ ansible_hostname }}_02_{{ date_for_file.stdout}}.txt'
        dest: '/ansible/audit/linux_severs/'
        flat: yes
